---
trigger: none

pr:
  branches:
    include:
      - main

pool:
  name: "Azure Pipelines"
  vmImage: "ubuntu-latest"

steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.10"
      addToPath: true

  - script: |
      curl -sSL https://install.python-poetry.org | python3 -
      echo "$HOME/.local/bin" >> $GITHUB_PATH
      poetry --version
    displayName: "Install Poetry"

  - script: |
      poetry lock
      poetry install --no-root --all-extras
    displayName: "Install Dependencies"

  - script: |
      make check-all
    displayName: "Run Linters"

  # Subproject-specific test steps will be added by create_python_subproject.sh